version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: blockpass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    # load all your .env vars, including DB_BACKEND, FILE_PATH, VAULT_KEY, etc.
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app         # your code + .env
      - ./data:/data   # for file‑backend JSON
    # on startup: if file‑backend, init the JSON files; then launch uvicorn
    command: >
      /bin/sh -c "
        if [ \"$DB_BACKEND\" = \"file\" ]; then
          mkdir -p /data &&
          [ -f /data/blockpass_users.json ] || echo '[]' > /data/blockpass_users.json &&
          [ -f /data/blockpass_vault.json ] || echo '[]' > /data/blockpass_vault.json;
        fi
        uvicorn app.main:app --host 0.0.0.0 --reload
      "

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  db_data: